### DISCUSSION TITLE
Automation

### DISCUSSION THREAD

**Discussion by derwana** [TheGuyDanish/CM4_MATX#44] [General]
This thread is for showing all of my automation attempts.

I just dived into [KiBot](https://github.com/INTI-CMNB/kibot) and [KiAuto](https://github.com/INTI-CMNB/KiAuto) for generating PDF, Gerber and STEP files.

So i installed current releases of both repos and put the following `cm4_matx.kibot.yaml` file into the projects root folder.
```yml
# documentation at https://github.com/INTI-CMNB/kibot

kibot:
  version: 1

preflight:
  # [boolean=false] Zones are filled before doing any operation involving PCB layers
  check_zone_fills: true
  # [list(dict)] A list of entries to filter out ERC/DRC messages
  #filters: 
  #  - filter: 'Filter description'
  #    error: '10'
  #    regex: 'Regular expression to match'
  # [boolean=false] Option for `run_drc`. Ignores the unconnected nets. Useful if you didn't finish the routing
  #ignore_unconnected: true
  # [boolean=false] Runs the DRC (Distance Rules Check). To ensure we have a valid PCB
  #run_drc: true
  # [boolean=false] Runs the ERC (Electrical Rules Check). To ensure the schematic is electrically correct
  #run_erc: true
  # [boolean=false] Update the XML version of the BoM (Bill of Materials).
  update_xml: true


outputs:
  ### GERBERS ######################################################
  - name: 'gerbers'
    comment: "Exporting the PCB to Gerbers."
    type: 'gerber'
    dir: 'gerber'
    options:
      # generic layer options
      exclude_edge_layer: false
      exclude_pads_from_silkscreen: false
      plot_sheet_reference: false
      plot_footprint_refs: true
      plot_footprint_values: true
      force_plot_invisible_refs_vals: false
      tent_vias: true
      line_width: 0.15
      # gerber options
      use_aux_axis_as_origin: false
      subtract_mask_from_silk: true
      use_protel_extensions: false
      gerber_precision: 4.5
      create_gerber_job_file: true
      use_gerber_x2_attributes: true
      use_gerber_net_attributes: false
    layers:
      - 'F.Cu'
      - 'B.Cu'

  - name: 'gerber_drills'
    comment: 'Exporting drillings of PCB to Gerbers.'
    type: 'gerb_drill'
    dir: 'gerber'
    options:
      # [dict|string] [hpgl,ps,gerber,dxf,svg,pdf] format for a graphical drill map.
      # Not generated unless a format is specified
      map:
        # [string='%f-%i%v.%x'] name for the map file, KiCad defaults if empty (%i='PTH_drill_map'). Affected by global options
        output: ''
        # [string='pdf'] [hpgl,ps,gerber,dxf,svg,pdf] format for a graphical drill map
        type: 'gerber'
      # [string='%f-%i%v.%x'] name for the drill file, KiCad defaults if empty (%i='PTH_drill'). Affected by global options
      output: ''
      # [boolean=false] use the auxiliar axis as origin for coordinates
      use_aux_axis_as_origin: false

  - name: 'position'
    comment: 'Generating position information for the PCB components.'
    type: 'position'
    dir: 'gerber'
    options:
      # [list(dict)|list(string)] which columns are included in the output
      #columns:
        # [string=''] [Ref,Val,Package,PosX,PosY,Rot,Side] Internal name
      #  id: ''
        # [string=''] Name to use in the outut file. The id is used when empty
      #  name: ''
      # [string|list(string)=''] Name of the filter to mark components as not fitted.
      # A short-cut to use for simple cases where a variant is an overkill
      #dnf_filter: ''
      # [string='ASCII'] [ASCII,CSV] format for the position file
      format: 'CSV'
      # [boolean=true] only include the surface mount components
      only_smd: true
      # [string='%f-%i%v.%x'] output file name (%i='top_pos'|'bottom_pos'|'both_pos', %x='pos'|'csv'). Affected by global options
      output: 'positions.csv'
      # [boolean=true] generate two separated files, one for the top and another for the bottom
      separate_files_for_front_and_back: true
      # [string='millimeters'] [millimeters,inches] units used for the positions
      units: 'millimeters'
      # [string=''] Board variant to apply
      #variant: ''

  ### PDFs ##########################################################
  - name: 'pdf-sch'
    comment: 'Exporting the PCB to PDF. Suitable for printing.'
    type: 'pdf_sch_print'
    dir: 'pdf' 
    options:
      # [string|list(string)=''] Name of the filter to mark components as not fitted.
      # A short-cut to use for simple cases where a variant is an overkill
      #dnf_filter: ''
      # [string='%f-%i%v.%x'] filename for the output PDF (%i=layers, %x=pdf). Affected by global options
      output: 'CM4_MATX_SCH.pdf'
      # [string=''] Board variant to apply
      #variant:

  - name: 'pdf-pcb'
    comment: "Exporting the PCB as PDF"
    type: 'pdf_pcb_print'
    dir: 'pdf'
    options:
      # [string|list(string)=''] Name of the filter to mark components as not fitted.
      # A short-cut to use for simple cases where a variant is an overkill
      #dnf_filter: ''
      # [string='full'] what to use to indicate the drill places, can be none, small or full (for real scale)
      drill_marks: 'full'
      # [boolean=false] print mirrored (X axis inverted). ONLY for KiCad 6
      mirror: false
      # [boolean=false] print in black and white
      monochrome: false
      # [string='%f-%i%v.%x'] filename for the output PDF (%i=layers, %x=pdf). Affected by global options
      output: 'CM4_MATX_PCB.pdf'
      # `output_name` is an alias for `output`
      # [boolean=true] include the title-block
      plot_sheet_reference: true
      # [number=1.0] scale factor (0 means autoscaling)
      scaling: 1.0
      # [boolean=false] print layers in separated pages
      separated: false
      # [string=''] Board variant to apply
      #variant: ''
    layers: 'all'

  ### STEP ##########################################################
  - name: 'step'
    comment: 'Exporting the PCB as a 3D model.'
    type: 'step'
    dir: 'step'
    options:
      # [string|list(string)=''] Name of the filter to mark components as not fitted.
      # A short-cut to use for simple cases where a variant is an overkill
      #dnf_filter: ''
      # [boolean=true] use metric units instead of inches
      metric_units: true
      # [number=-1] the minimum distance between points to treat them as separate ones (-1 is KiCad default: 0.01 mm)
      min_distance: -1
      # [boolean=false] used to exclude 3D models for components with 'virtual' attribute
      no_virtual: false
      # [string='grid'] determines the coordinates origin. Using grid the coordinates are the same as you have in the design sheet.
      # The drill option uses the auxiliar reference defined by the user.
      # You can define any other origin using the format 'X,Y', i.e. '3.2,-10'
      origin: 'grid'
      # [string='%f-%i%v.%x'] name for the generated STEP file (%i='3D' %x='step'). Affected by global options
      output: 'CM4_MATX.step'
      # [string=''] Board variant to apply
      #variant: ''
```

By running `kibot -b ./KiCad/CM4_MATX.kicad_pcb` from the root folder it creates the folders `gerber`, `pdf` and `step` and populates these with the generated files. It also generates a BoM file named `CM4_MATX.csv` at the projects root.

It can also be used as [Github Action](https://github.com/INTI-CMNB/KiBot#usage-of-github-actions) on push or merge (needs Docker).

**Comment by derwana** [comment]
Also added a little python script for generating a jpg from pdf:

```python
# needs packages pdf2image, pillow

# import modules
import os
from pdf2image import convert_from_path 
from PIL import Image 

  
# open pdf 
images = convert_from_path('./CM4_MATX_PCB.pdf') 

# convert to jpg
for img in images: 
    img.save('./CM4_MATX_PCB_tmp.jpg', 'JPEG')

# open jpg
img = Image.open(r"./CM4_MATX_PCB_tmp.jpg") 

# set cropping (px) 
left = 200
top = 100
right = 2300
bottom = 2200

# crop image  
img_cropped = img.crop((left, top, right, bottom)) 

# save image
img_cropped.save("./CM4_MATX_PCB.jpg")

# remove *tmp.jpg
os.remove("./CM4_MATX_PCB_tmp.jpg")
```

**Comment by TheGuyDanish** [comment]
Looks good. I'll try and get to testing putting this into the repo in the next couple of days. I'm more looking towards the automated PCB and schematic files than anything at the moment, since we aren't in a state to pass ERC/DRC checks anyway.

**Reply by derwana** [reply]
In the config for KiBot i disabled `run_drc`, `run_erc` so it does not throw any  warnings and errors - just generates the files.

**Reply by derwana** [reply]
Run KiBot prior to the Python script, else no PDFs are found.

**Comment by derwana** [comment]
Python function for exporting a VRML file: [ExportVRML_File()](https://docs.kicad.org/doxygen-python/classpcbnew_1_1VRML__WRITER.html)

**Reply by derwana** [reply]
VRML exporting is yet not supported via Python.

**Comment by TheGuyDanish** [comment]
IT LIVES

https://github.com/TheGuyDanish/CM4_MATX/runs/1617944772

**Reply by geerlingguy** [reply]
Woah, nice!

**Reply by TheGuyDanish** [reply]
It now produces standalone artifacts, rather than a large zip as of the latest commit. (The STEP model does take up quite a bit of space).
![image](https://user-images.githubusercontent.com/5776313/103227234-c012b080-4925-11eb-89c9-f2a9cfa642c3.png)

I had to neuter it a little in order to get it to run. For some reason, the XML BOM export caused it to fail, but I'm not sure why. It looks similar to the issue encountered in INTI-CMNB/KiBot#10, so it might be a problem with our schematic symbols and the like.

**Reply by derwana** [reply]
May add the following to `/.github/workflows/kicad.yml` as well:

```yml
- name: setup python
  uses: actions/setup-python@v2
  with:
    python-version: 3.8
- name: install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install pdf2image pillow
- name: execute python script # run pdf2jpg.py to get jpg of the latest CM4_MATX_PCB.pdf
  run: |
    python pdf2jpg.py
- name: upload JPG of CM4_MATX_PCB.pdf
  uses: actions/upload-artifact@v2
  with:
    name: CM4_MATX_PCB.jpg
    path: output/CM4_MATX_PCB.jpg
```

With `pdf2jpg.py` beeing the python script some post above. I am not completely sure where to put the Python script tho (projects root folder i asume).
